# Exynos7870 uses the pre-ACPM, clock/regulator based devfreq binding.
obj-$(CONFIG_ARM_EXYNOS7870_DEVFREQ) += exynos7870-devfreq.o
obj-$(CONFIG_ARM_EXYNOS7870_BUS_DEVFREQ) += exynos7870_bus_mif.o \
					    exynos7870_bus_int.o \
					    exynos7870_bus_disp.o \
					    exynos7870_bus_cam.o
